baseURL = 'https://tweed.cloud/'
languageCode = 'en-us'
title = 'Tweed Cloud'

disableKinds = ['taxonomy', 'term']

[params]
  description = 'Website design, hosting, and consultation in Murwillumbah (Northern Rivers). I can physically assist local clients or work remotely. Call 0406860031.'
