baseURL = 'https://tweed.cloud/'
languageCode = 'en-us'
title = 'Tweed Cloud'

disableKinds = ['taxonomy', 'term']
enableGitInfo = true

[params]
  description = 'Website design, hosting, and consultation in Murwillumbah (Northern Rivers). I can physically assist local clients or work remotely. Call 0406860031.'
  sameAs = [
    'https://github.com/JordanDavidEvans',
    'https://www.linkedin.com/in/jordan-evans-37a211212',
    'https://www.instagram.com/da_jordo/'
  ]

  [[params.serviceCatalog]]
    name = 'Digital operations & automation'
    description = 'Stock tracking workflows, client onboarding forms, booking systems, CRM/email setup, team communication stack.'

  [[params.serviceCatalog]]
    name = 'Website & growth'
    description = 'QA site audits, accessibility checks, performance and Core Web Vitals, on-page SEO, analytics/GTM validation.'

  [[params.serviceCatalog]]
    name = 'IT support & hardware'
    description = 'Workstation and network recommendations, upgrade paths, backup and continuity planning, email/domain hygiene.'

  [[params.serviceCatalog]]
    name = 'Security & risk'
    description = 'Advisory vulnerability review, uptime and downtime risk assessment, mitigation roadmap.'

  [params.seo]
    organization = true

[sitemap]
  changefreq = 'monthly'
  priority = 0.5
  filename = 'sitemap.xml'
